=== git-uni/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/rutas" elementFormDefault="qualified" targetNamespace="http://tempuri.org/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tipo" />
				<xs:element ref="transporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="tipoPersona" />
				<xs:element ref="lugarInicio" />
				<xs:element ref="direccionInicio" />
				<xs:element ref="coordenadas" />
				<xs:element ref="referencias" />
				<xs:element ref="notaRecomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tipo" type="xs:string" />
	<xs:element name="transporte" type="xs:string" />
	<xs:element name="fechaInicio" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="duracion" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="tipoPersona" type="xs:string" />
	<xs:element name="lugarInicio" type="xs:string" />
	<xs:element name="direccionInicio" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:double" />
	<xs:element name="latitud" type="xs:double" />
	<xs:element name="altitud" type="xs:double" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="notaRecomendacion" type="xs:integer" />
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element minOccurs="1"  ref="fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
</xs:schema>

=== git-uni/SEW/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://tempuri.org/rutas"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tempuri.org/rutas rutas.xsd">

    <ruta>
        <nombre>Excursión de un Día a los Acantilados de Moher</nombre>
        <tipo> Senderismo </tipo>
        <transporte> A pie  </transporte>
        <fechaInicio> 2023-10-25 </fechaInicio>
        <horaInicio> 09:00:00 </horaInicio>
        <duracion> PT5H </duracion>
        <agencia> IrlandaTravel </agencia>
        <descripcion> Ruta a pie hasta los acantilados de Moher  </descripcion>
        <tipoPersona> Mayores de 9 años </tipoPersona>
        <lugarInicio> Parada de bus Eireann </lugarInicio>
        <direccionInicio> Ēireann Bus Stop in Cliffs of Moher, Moher Rd, Irlanda </direccionInicio>

        <coordenadas>
            <longitud>-9.4256</longitud>
            <latitud>52.9703</latitud>
            <altitud>140</altitud>
        </coordenadas>

        <referencias>
            <referencia> https://es.wikipedia.org/wiki/Acantilados_de_Moher </referencia>
            <referencia> https://en.wikipedia.org/wiki/O%27Brien%27s_Tower  </referencia>
            <referencia> https://en.wikipedia.org/wiki/County_Clare         </referencia>
        </referencias>

        <notaRecomendacion> 8 </notaRecomendacion>

        <hitos>
            <hito>
                <nombre> O'Brien's Tower </nombre>

                <coordenadas>
                    <longitud>-9.4306</longitud>
                    <latitud>52.9731</latitud>
                    <altitud>188</altitud>
                </coordenadas>

                <distancia unidades="km"> 2  </distancia>

                <fotografias>
                    <foto> oBriensTower.png </foto>
                </fotografias>
            </hito>

            <hito>
                <nombre>Hag's Head</nombre>
                <coordenadas>
                    <longitud>-9.4678</longitud>
                    <latitud>52.9481</latitud>
                    <altitud>130</altitud>
                </coordenadas>
                <distancia unidades="km">5</distancia>
                <fotografias>
                    <foto>hagsHead.png</foto>
                </fotografias>
            </hito>

            <hito>
                <nombre>Cliffs View Cafe</nombre>
                <coordenadas>
                    <longitud>-9.4369</longitud>
                    <latitud>52.9642</latitud>
                    <altitud>103</altitud>
                </coordenadas>
                <distancia unidades="km">8</distancia>
                <fotografias>
                    <foto>cliffsCafe.png</foto>
                </fotografias>
            </hito>
        </hitos>
    </ruta>

    <ruta>
        <nombre>Excursión a la Calzada del Gigante</nombre>
        <tipo> Senderismo y monumentos </tipo>
        <transporte> A pie y Tren </transporte>
        <fechaInicio> 2023-11-12 </fechaInicio>
        <horaInicio> 09:30:00 </horaInicio>
        <duracion> PT6H </duracion>
        <agencia> IrlandaAdventure </agencia>
        <descripcion> Ruta a pie a la Calzada del Gigante, un sitio natural impresionante en la costa norte de Irlanda.  </descripcion>
        <tipoPersona> Mayores de 8 años </tipoPersona>
        <lugarInicio> Centro de Visitantes de la Calzada del Gigante </lugarInicio>
        <direccionInicio> National Trust - Giant's Causeway Visitor Centre </direccionInicio>

        <coordenadas>
            <longitud>-6.5114</longitud>
            <latitud>55.2408</latitud>
            <altitud>45</altitud>
        </coordenadas>

        <referencias>
            <referencia> https://es.wikipedia.org/wiki/Calzada_del_Gigante                       </referencia>
            <referencia> https://www.nationaltrust.org.uk/visit/northern-ireland/giants-causeway </referencia>
            <referencia> https://whc.unesco.org/es/list/369                                      </referencia>
        </referencias>

        <notaRecomendacion> 6 </notaRecomendacion>

        <hitos>
            <hito>
                <nombre> Giant's Causeway Viewpoint </nombre>

                <coordenadas>
                    <longitud>-6.5103</longitud>
                    <latitud>55.2389</latitud>
                    <altitud>49</altitud>
                </coordenadas>

                <distancia unidades="km"> 5  </distancia>

                <fotografias>
                    <foto> calzadaDelGigante.png </foto>
                </fotografias>

                <videos>
                    <video> calzadaDelGigante.mp4</video>
                </videos>
            </hito>

            <hito>
                <nombre>Centro de Visitantes de la Calzada del Gigante</nombre>
                <coordenadas>
                    <longitud>-6.5178</longitud>
                    <latitud>55.2336</latitud>
                    <altitud>45</altitud>
                </coordenadas>
                <distancia unidades="km">8</distancia>
                <fotografias>
                    <foto>centroDeVisitantes.png</foto>
                </fotografias>
                <videos>
                    <video>centroDeVisitantes.mp4</video>
                </videos>
            </hito>

            <hito>
                <nombre>Ruta de Senderismo de la Calzada del Gigante</nombre>
                <coordenadas>
                    <longitud>-6.5172</longitud>
                    <latitud>55.2372</latitud>
                    <altitud>15</altitud>
                </coordenadas>
                <distancia unidades="km">15</distancia>
                <fotografias>
                    <foto>rutaDeSenderismo.png</foto>
                </fotografias>
                <videos>
                    <video>rutaDeSenderismo.mp4</video>
                </videos>
            </hito>

        </hitos>
    </ruta>

    <ruta>
        <nombre>Excursión al Parque Nacional de Wicklow</nombre>
        <tipo> Senderismo, Naturaleza y Monumentos </tipo>
        <transporte> A pie y Bus </transporte>
        <fechaInicio> 2023-12-17 </fechaInicio>
        <horaInicio> 10:00:00 </horaInicio>
        <duracion> PT4H </duracion>
        <agencia> IrlandaTravel </agencia>
        <descripcion> Ruta a pie para explorar el hermoso Parque Nacional de Wicklow en el este de Irlanda.  </descripcion>
        <tipoPersona> Mayores de 12 años </tipoPersona>
        <lugarInicio> Centro de Visitantes del Parque Nacional de Wicklow </lugarInicio>
        <direccionInicio> Wicklow Mountains National Park, Greenan, Condado de Wicklow, Irlanda </direccionInicio>

        <coordenadas>
            <longitud>-6.3108</longitud>
            <latitud>53.1431</latitud>
            <altitud>150</altitud>
        </coordenadas>

        <referencias>
            <referencia> https://es.wikipedia.org/wiki/Parque_Nacional_de_Wicklow_Mountains </referencia>
            <referencia> https://www.nationalparks.ie/wicklow/                              </referencia>
            <referencia> https://es.wikipedia.org/wiki/Montes_Wicklow                       </referencia>
        </referencias>

        <notaRecomendacion> 9 </notaRecomendacion>

        <hitos>
            <hito>
                <nombre> Cascada de Powerscourt </nombre>
                <coordenadas>
                    <longitud>-6.2111</longitud>
                    <latitud>53.1461</latitud>
                    <altitud>220</altitud>
                </coordenadas>


                <distancia unidades="km"> 5  </distancia>

                <fotografias>
                    <foto> powerscourtCascada.png </foto>
                </fotografias>
            </hito>

            <hito>
                <nombre>Glendalough Upper Lake</nombre>
                <coordenadas>
                    <longitud>-6.3628</longitud>
                    <latitud>53.0053</latitud>
                    <altitud>143</altitud>
                </coordenadas>
                <distancia unidades="km">8</distancia>
                <fotografias>
                    <foto>glendaloughUpperLake.png</foto>
                </fotografias>
            </hito>

            <hito>
                <nombre>Paseo por el Wicklow Way</nombre>
                <coordenadas>
                    <longitud>-6.2544</longitud>
                    <latitud>53.0853</latitud>
                    <altitud>200</altitud>
                </coordenadas>
                <distancia unidades="km">12</distancia>
                <fotografias>
                    <foto>wicklowWayPaseo.png</foto>
                </fotografias>
            </hito>


        </hitos>
    </ruta>
</rutas>
